language: cpp
compiler:
- gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl-* libglew-dev libglm-dev libboost-all-dev libboost-program-options-dev
branches:
  only:
    - master
notifications:
  email: true
os:
- linux
- osx

sudo: true
